name: Deploy on Main Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Server deploy on Lightsail server
        run: |
          deploy_server.sh
